"""Fixed legal text (ARCHITECTURE.md Section 7.5). Do not edit without legal review."""

LEGAL_DISCLAIMER = (
    "AI-Assisted Analysis — Not Evidence. This content was generated by CrimeScene AI, "
    "an automated analysis tool, from the referenced footage. It is investigative decision "
    "support only. It may contain errors, including missed persons or objects, incorrect "
    "tracking, and mistaken interpretation of events. Every statement carries a confidence "
    "score and timestamp citation and must be independently verified by a qualified human "
    "investigator against the original footage before any investigative, prosecutorial, or "
    "legal use. Person labels (A, B, C…) are anonymous tracking labels, not identifications. "
    "Gender values are algorithmic estimates. Suspect-match results indicate algorithmic "
    "facial similarity only and do not constitute identification. This output is not a "
    "statement of fact, guilt, or legal conclusion."
)

LEGAL_DISCLAIMER_SHORT = "AI-assisted analysis — verify against footage before use. Not evidence."
