"""Initial schema: all tables from app.models, plus the pgvector extension.

This first migration creates the schema from the SQLAlchemy metadata (the single
source of truth in Phase 0-9). Subsequent migrations must be normal autogenerated
Alembic revisions.
"""
from alembic import op

from app.core.db import Base
import app.models  # noqa: F401

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
